image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: TemplateBuilder.sln
  verbosity: minimal

after_test: 
  - cmd: "\"packages/opencover/4.7.922/tools/OpenCover.Console.exe\" -target:\"c:/program files/dotnet/dotnet.exe\" -targetargs:\"test -f netcoreapp3.1 -c Release /p:DebugType=full\" -filter:\"+[*Repopulator*]*\"  -output:coverage.xml -register:appveyor -oldStyle -hideskipped:File"
  - codecov -f "coverage.xml"
  - dotnet publish -r win-x64